// <auto-generated />
namespace SistemaAgendaORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class boolSexo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(boolSexo));
        
        string IMigrationMetadata.Id
        {
            get { return "201601052251343_bool-Sexo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
